# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('whois', '0002_delete_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('Id_link', models.TextField()),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
    ]
