# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whois', '0003_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='Id_link',
        ),
        migrations.RemoveField(
            model_name='links',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='links',
            name='fecha',
        ),
    ]
