# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-04 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whois', '0004_auto_20180104_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Links',
        ),
    ]
